export interface Scenario {
  claimNumber: string;
  firstPartyName: string;
  firstPartySurname: string;
  firstPartyId: string;
  firstPartyVehicle: string;
  firstPartyDescription: string;
  witnesses: string;
  thirdPartyName: string;
  thirdPartySurname: string;
  thirdPartyVehicle: string;
  thirdPartyVehicleVin: string;
  thirdPartyLicencePlate: string;
  thirdPartyInsuranceCompany: string;
  thirdPartyPolicyNumber: string;
  thirdPartyId: string;
  thirdPartyVersion: string;
  /** Accident report number (police report number); max 20 characters when normalized. */
  accidentReportNumber?: string;
  /** Accident date. */
  accidentDate?: string;
  /** Accident time. */
  accidentTime?: string;
  /** Accident place/address. */
  accidentPlace?: string;
  /** Third party vehicle colour (generated by AI). */
  thirdPartyVehicleColour?: string;
  /** Base repair cost in ZAR (assessment report amount). Used for consistency across costing docs. */
  assessmentAmount?: number;
  /** Final costing report amount in ZAR. Must be 10% above assessmentAmount. */
  finalCostingReportAmount?: number;
  /** Panel beater quote 1 total in ZAR (uninsured flow). */
  quote1Amount?: number;
  /** Panel beater quote 2 total in ZAR (uninsured flow). */
  quote2Amount?: number;
  /** Panel beater quote 3 total in ZAR (uninsured flow). */
  quote3Amount?: number;
}

export type ClaimType = 'insured' | 'uninsured' | 'firstParty';

export interface DocumentRequirement {
  id: string;
  title: string;
  description: string;
  documentGuidelines?: string;
}

export interface AppSettings {
  defaults: {
    thirdPartyId: string;
    thirdPartyName: string;
    thirdPartySurname: string;
    thirdPartyContactNumber: string;
    thirdPartyEmail: string;
    thirdPartyVehicle: string;
    thirdPartyLicencePlate: string;
    thirdPartyVehicleVin: string;
    thirdPartyEngineNumber: string;
    thirdPartyInsuranceCompany: string;
    firstPartyName: string;
    firstPartySurname: string;
    firstPartyId: string;
    firstPartyVehicle: string;
    /** First party vehicle colour (e.g. "White"). */
    firstPartyVehicleColour?: string;
    /** First party vehicle registration (SA format). */
    firstPartyVehicleRegistration?: string;
    /** Bank account number for generated proof-of-bank-account documents. */
    bankAccountNumber: string;
    /** Bank name (e.g. Absa). */
    bankName: string;
    /** Branch / universal branch code. */
    branchCode: string;
    /** Insurer company registration number (e.g. Discovery Ltd). Used for insured proof of bank account. */
    insurerRegistrationNumber: string;
  };
}

export const DEFAULT_SETTINGS: AppSettings = {
  defaults: {
    thirdPartyId: '9001015000087',
    thirdPartyName: 'Eren',
    thirdPartySurname: 'Yeager',
    thirdPartyContactNumber: '083 284 1662',
    thirdPartyEmail: 'erenyeager@gmail.com',
    thirdPartyVehicle: 'Red Suzuki Swift 2023',
    thirdPartyLicencePlate: 'CPT123WC',
    thirdPartyVehicleVin: '1G6DW677170113927',
    thirdPartyEngineNumber: 'K12M123456',
    thirdPartyInsuranceCompany: 'Discovery',
    firstPartyName: 'John',
    firstPartySurname: 'Doe',
    firstPartyId: '8501015000081',
    firstPartyVehicle: 'White Fiat 500',
    firstPartyVehicleColour: 'White',
    firstPartyVehicleRegistration: 'CA 123-456 GP',
    bankAccountNumber: '12222222221',
    bankName: 'Absa',
    branchCode: '632005',
    insurerRegistrationNumber: '2009/011882/06',
  }
};

export const INSURED_DOCS: DocumentRequirement[] = [
  { id: 'letter_of_demand', title: 'Letter of Demand', description: 'Formal letter demanding payment.' },
  { id: 'assessment_report', title: 'Assessment Report / Quote', description: 'Assessment report for the vehicle or panel beater quote.' },
  { id: 'final_costing_report', title: 'Final Costing Report', description: 'Final costing report for the vehicle.' },
  { id: 'proof_of_bank_account_insured', title: 'Proof of Bank Account', description: 'Bank letter or stamped confirmation in the third party insurer\'s name with company registration for payment.' },
];

export const LEGAL_DOCS: DocumentRequirement[] = [
  {
    id: 'summons',
    title: 'Summons',
    description: 'Civil summons document to commence recovery proceedings against the third party. Lay this out like a South African civil summons pack. Include a court heading, case reference details, plaintiff and defendant details, cause of action tied to the motor vehicle accident, an amount claimed placeholder or realistic damages wording, and a signature block for the issuing attorney or registrar. Keep it formal, legal, and document-heavy rather than handwritten.',
  },
  {
    id: 'return_of_service',
    title: 'Return of Service',
    description: 'Sheriff return confirming how and when the summons was served. Lay this out like a South African sheriff return of service. Include the court heading, case reference details, the document served, date and time of service, method of service, address served at, recipient details if applicable, and a sheriff signature or stamp area. Keep it formal and administrative.',
  },
];

export const FIRST_PARTY_DOCS: DocumentRequirement[] = [
  { id: 'first_party_damage_photo_1', title: 'First Party Damage Photo 1', description: 'Photo of damage to our insured vehicle (close-up).' },
  { id: 'first_party_damage_photo_2', title: 'First Party Damage Photo 2', description: 'Photo showing the accident scene / first party vehicle.' },
  { id: 'first_party_damage_photo_3', title: 'First Party Odometer Photo', description: 'Close-up of the odometer / mileage reading on our insured vehicle.' },
];

export const UNINSURED_DOCS: DocumentRequirement[] = [
  { id: 'claim_form', title: 'Third Party Claim Form', description: 'Document with all the claim form requirements.' },
  { id: 'quote_1', title: 'Panel Beater Quote 1', description: 'First unique quote.' },
  { id: 'quote_2', title: 'Panel Beater Quote 2', description: 'Second unique quote.' },
  { id: 'quote_3', title: 'Panel Beater Quote 3', description: 'Third unique quote.' },
  { id: 'damage_photo_1', title: 'Damage Photo 1', description: 'Photo of the accident/vehicle.' },
  { id: 'damage_photo_2', title: 'Damage Photo 2', description: 'Photo of the accident/vehicle.' },
  { id: 'damage_photo_3', title: 'Damage Photo 3', description: 'Photo of the accident/vehicle (optional).' },
  { id: 'id_document', title: 'ID Document', description: 'ID document for the involved party.' },
  { id: 'natis_document', title: 'Natis Document', description: 'Natis document for the involved vehicle.' },
  { id: 'no_claims_letter', title: 'No Claims Letter / Affidavit', description: 'Confirming there is no insurance claim.' },
  { id: 'licence_disc', title: 'Licence Disc', description: 'Licence disc on the vehicle screen, showing the VIN.' },
  { id: 'proof_of_bank_account', title: 'Proof of Bank Account', description: 'Bank letter or stamped confirmation showing the third party account details for payment.' },
];

export const ALL_DOCS = [...INSURED_DOCS, ...LEGAL_DOCS, ...UNINSURED_DOCS, ...FIRST_PARTY_DOCS];

declare global {
  interface Window {
    aistudio?: {
      hasSelectedApiKey: () => Promise<boolean>;
      openSelectKey: () => Promise<void>;
    };
  }
}
