import type { VercelRequest, VercelResponse } from "@vercel/node";
import { GoogleGenAI } from "@google/genai";

interface Scenario {
  claimNumber: string;
  firstPartyName: string;
  firstPartySurname: string;
  firstPartyId: string;
  firstPartyVehicle: string;
  firstPartyDescription: string;
  witnesses: string;
  thirdPartyName: string;
  thirdPartySurname: string;
  thirdPartyId: string;
  thirdPartyVersion: string;
}

interface DocumentRequirement {
  id: string;
  title: string;
  description: string;
  documentGuidelines?: string;
}

interface GenerateImageRequestBody {
  scenario: Scenario;
  requirement: DocumentRequirement;
  exampleBase64: string | null;
}

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
): Promise<void> {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed" });
    return;
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    res.status(500).json({ error: "Server is missing API key configuration" });
    return;
  }

  const { scenario, requirement, exampleBase64 } =
    req.body as GenerateImageRequestBody;

  if (!scenario || !requirement) {
    res
      .status(400)
      .json({ error: "Missing required fields: scenario, requirement" });
    return;
  }

  try {
    const ai = new GoogleGenAI({ apiKey });

    const prompt = `
      You are an expert document generator for a South African insurance system.
      Generate a realistic image of a document based on the following scenario and requirements.
      All information MUST match the scenario exactly.

      Scenario Context:
      - Claim Number: ${scenario.claimNumber}
      - First Party (Our Insured Driver):
        - Name: ${scenario.firstPartyName} ${scenario.firstPartySurname}
        - ID Number: ${scenario.firstPartyId}
        - Vehicle: ${scenario.firstPartyVehicle}
        - Description of accident: ${scenario.firstPartyDescription}
        - Witnesses: ${scenario.witnesses}
      - Third Party:
        - Name: ${scenario.thirdPartyName} ${scenario.thirdPartySurname}
        - ID Number: ${scenario.thirdPartyId}
        - Version of events: ${scenario.thirdPartyVersion}
        - Note: The third party must never be fully at fault (there is always a liability claim against our driver).

      Document to Generate:
      - Title: ${requirement.title}
      - Description: ${requirement.description}
      - Document Guidelines: ${
        requirement.documentGuidelines ?? "None provided."
      }

      ${
        exampleBase64
          ? "An example document is provided as an image. Please use it as a structural and stylistic reference, but fill it with the scenario information."
          : "Please generate a realistic looking document from scratch."
      }

      IMPORTANT:
      - The document generated are primarily for the third party to make a liability claim against our driver. Hence, the first party context is only relevant for the claim form and the letter of demand.
    `;

    const parts: Array<
      { text: string } | { inlineData: { mimeType: string; data: string } }
    > = [{ text: prompt }];

    if (exampleBase64) {
      const matches = exampleBase64.match(/^data:(.+);base64,(.+)$/);
      if (matches && matches.length === 3) {
        parts.unshift({
          inlineData: {
            mimeType: matches[1],
            data: matches[2],
          },
        });
      }
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-image-preview",
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "3:4",
          imageSize: "1K",
        },
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts ?? []) {
      if (part.inlineData) {
        res.status(200).json({
          imageData: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`,
        });
        return;
      }
    }

    res.status(500).json({ error: "No image was generated by the model" });
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : "Unknown error";
    res.status(500).json({ error: msg });
  }
}
